# Generated by Django 2.2.1 on 2019-06-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type_of_user',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('user', 'User')], default='user', max_length=100),
        ),
    ]
