# Generated by Django 2.2.1 on 2019-06-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_business_category_typebusiness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='country',
            new_name='type_of_business',
        ),
    ]
