# Generated by Django 2.2.1 on 2019-06-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='type_of_business',
            new_name='typebusiness',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type_of_business',
            new_name='typebusiness',
        ),
    ]
