# Generated by Django 2.2.1 on 2019-06-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_auto_20190610_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.Business'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
